name: Final Project Web and API Automation Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  automation-JayJayFinalProject:
    runs-on: ubuntu-latest # windows-latest, macos-latest, ubuntu-18.04

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      # Install Chrome and ChromeDriver
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: stable #bisa pakai 'headless' (Jika ingin menjalankan Chrome dalam mode headless) tanpa interaksi

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 'matching-chrome'
        env:
          CHROME_BIN: google-chrome

      # Setup gradlew and build project
      - name: Setup gradlew and Build
        run: |
          chmod +x gradlew # make gradlew executable
          ./gradlew build # Run the build task before tests

      - name: Run Tests
        run: ./gradlew clean test

      # Archive test results (pastikan folder ini sesuai output test Anda)
      - name: Archive test results
        uses: actions/upload-artifact@v4.6.2
        if: always() # bisa diganti dengan success(), failed(), canceled(); tergantung kebutuhan tests
        with:
          name: Final Project Web and API Automation Workflow
          path: target/cucumber-reports.html

